name: Build LibreWolf from Source

on:
  schedule:
    - cron: "0 0 * * 1"  # Runs every Monday at midnight UTC
  push:
    branches:
      - master
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest  # Use an Arch Linux container

    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git

      - name: Clone LibreWolf Arch repository
        run: git clone --depth=1 https://gitlab.com/librewolf-community/browser/arch.git librewolf

      - name: Import Mozilla GPG key
        run: gpg --recv-key EBE41E90F6F12F6D

      - name: Build LibreWolf
        run: |
          cd librewolf
          makepkg -si --noconfirm

      - name: Upload built package
        uses: actions/upload-artifact@v4
        with:
          name: librewolf-package
          path: librewolf/*.pkg.tar.zst
