name: Build LibreWolf from Source

on:
  schedule:
    - cron: "0 0 * * 1"  # Runs every Monday at midnight UTC
  push:
    branches:
      - master
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest  # Use an Arch Linux container

    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git sudo

      - name: Create non-root user
        run: |
          useradd -m builduser
          echo 'builduser ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
          chown -R builduser:builduser /home/builduser

      - name: Clone LibreWolf repository
        run: sudo -u builduser git clone --depth=1 https://gitlab.com/librewolf-community/browser/arch.git /home/builduser/librewolf

      - name: Import Mozilla GPG key
        run: sudo -u builduser gpg --recv-key EBE41E90F6F12F6D

      - name: Build LibreWolf
        run: |
          cd /home/builduser/librewolf
          sudo -u builduser makepkg -si --noconfirm

      - name: Upload built package
        uses: actions/upload-artifact@v4
        with:
          name: librewolf-package
          path: /home/builduser/librewolf/*.pkg.tar.zst
