name: Build ytdownloader-gui-bin

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest  # Use Arch Linux container

    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git sudo

      - name: Create non-root user
        run: |
          useradd -m builduser
          echo 'builduser ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
          chown -R builduser:builduser /home/builduser

      - name: Install `paru` (AUR helper)
        run: |
          sudo -u builduser git clone https://aur.archlinux.org/paru-bin.git /home/builduser/paru
          cd /home/builduser/paru
          sudo -u builduser makepkg -si --noconfirm

      - name: Install `electron30-bin`
        run: |
          sudo -u builduser paru -S --noconfirm --skipreview electron30-bin

      - name: Clone AUR package `ytdownloader-gui-bin`
        run: sudo -u builduser git clone --depth=1 https://aur.archlinux.org/ytdownloader-gui-bin.git /home/builduser/ytdownloader

      - name: Build `ytdownloader-gui-bin`
        run: |
          cd /home/builduser/ytdownloader
          sudo -u builduser makepkg -si --noconfirm

      - name: Upload built package
        uses: actions/upload-artifact@v4
        with:
          name: ytdownloader-gui-bin
          path: /home/builduser/ytdownloader/*.pkg.tar.zst
