name: Build LibreWolf on Ubuntu

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y wget tar git ccache
          wget http://mirrors.kernel.org/archlinux/iso/latest/archlinux-bootstrap-x86_64.tar.gz
          tar -xzf archlinux-bootstrap-x86_64.tar.gz

      - name: Set up Arch chroot
        run: |
          sudo mkdir -p /mnt/arch
          sudo mv root.x86_64 /mnt/arch/root
          sudo cp /etc/resolv.conf /mnt/arch/root/etc/resolv.conf
          sudo mount --bind /mnt/arch/root /mnt/arch/root
          echo "Server = https://mirror.rackspace.com/archlinux/\$repo/os/\$arch" | sudo tee /mnt/arch/root/etc/pacman.d/mirrorlist

      - name: Install base-devel inside Arch chroot
        run: |
          sudo chroot /mnt/arch/root /bin/bash -c "pacman -Syu --noconfirm && pacman -S --noconfirm base-devel git ccache"

      - name: Clone LibreWolf repo
        run: |
          sudo chroot /mnt/arch/root /bin/bash -c "git clone --depth=1 https://gitlab.com/librewolf-community/browser/arch.git /librewolf"

      - name: Import Mozilla GPG key
        run: |
          sudo chroot /mnt/arch/root /bin/bash -c "gpg --recv-key EBE41E90F6F12F6D"

      - name: Build LibreWolf
        run: |
          sudo chroot /mnt/arch/root /bin/bash -c "cd /librewolf && makepkg -si --noconfirm"

      - name: Upload built package
        uses: actions/upload-artifact@v4
        with:
          name: librewolf-package
          path: /mnt/arch/root/librewolf/*.pkg.tar.zst
