name: Build Mutter from main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git meson ninja-build \
            libglib2.0-dev libgtk-3-dev libx11-dev libxrandr-dev \
            libxinerama-dev libxi-dev libudev-dev libsystemd-dev \
            libgirepository1.0-dev libcanberra-gtk3-dev libinput-dev \
            libpipewire-0.3-dev libxcomposite-dev libxdamage-dev \
            libxext-dev libxfixes-dev libxrender-dev libxkbcommon-dev \
            libstartup-notification0-dev libwayland-dev wayland-protocols \
            libdrm-dev libegl1-mesa-dev libgbm-dev libgles2-mesa-dev \
            libjson-glib-dev libxkbfile-dev libpango1.0-dev libcairo2-dev \
            gnome-desktop3-dev

      - name: Clone Mutter main branch
        run: |
          git clone --branch main --depth 1 https://gitlab.gnome.org/GNOME/mutter.git
          cd mutter
          git submodule update --init --recursive

      - name: Configure and build Mutter
        run: |
          cd mutter
          meson setup build --prefix=/usr --buildtype=release
          ninja -C build

      - name: Package build (optional)
        run: |
          cd mutter
          DESTDIR=$PWD/pkg ninja -C build install
          tar -czf mutter-main-artifact.tar.gz -C pkg .

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: mutter-main-build
          path: mutter/mutter-main-artifact.tar.gz
