name: Build XanMod x64v2 Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git ncurses libelf cpio bc openssl \
            pahole xmlto python-sphinx graphviz imagemagick perl tar xz

      - name: Clone XanMod kernel from GitLab
        run: |
          git clone --depth=1 --branch master https://gitlab.com/xanmod/linux.git
          cd linux
          make x86_64_xanmod_v2_defconfig

      - name: Build kernel and modules
        run: |
          cd linux
          make -j$(nproc)
          make modules -j$(nproc)

      - name: Install modules and headers
        run: |
          cd linux
          mkdir -p ../out/mod ../out/headers ../out/kernel
          make modules_install INSTALL_MOD_PATH=../out/mod
          make headers_install INSTALL_HDR_PATH=../out/headers
          cp arch/x86/boot/bzImage ../out/kernel/
          cp System.map .config ../out/kernel/

      - name: Archive kernel as .tar.xz
        run: |
          cd out
          tar -cJf ../xanmod-x64v2-kernel.tar.xz *

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: xanmod-x64v2-kernel
          path: xanmod-x64v2-kernel.tar.xz
