name: Build Mutter-git inside Arch container

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (to get a workspace)
        uses: actions/checkout@v4

      - name: Install Docker if needed
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Clone Mutter-git AUR repo
        run: git clone https://aur.archlinux.org/mutter-git.git

      - name: Build inside Arch container using Docker
        run: |
          docker run --rm -v $PWD:/build -w /build archlinux:base-devel bash -c "
            pacman -Syu --noconfirm &&
            pacman -S --noconfirm git sudo &&
            useradd -m builder &&
            echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers &&
            chown -R builder /build &&
            sed -i 's/^#?VERIFYSIG=.*/VERIFYSIG=\"n\"/' /etc/makepkg.conf &&
            cd mutter-git &&
            sudo -u builder makepkg -s --noconfirm
          "

      - name: Upload built package
        uses: actions/upload-artifact@v3
        with:
          name: mutter-git-pkg
          path: mutter-git/*.pkg.tar.zst
