name: Build Mutter-git for Arch Linux

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel

    steps:
      - name: Install base-devel and git
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git sudo

      - name: Create build user (non-root)
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder .

      - name: Disable signature checking
        run: |
          sed -i 's/^#?PKGEXT=.*/PKGEXT=.pkg.tar.zst/' /etc/makepkg.conf
          sed -i 's/^#?USE_COLOR.*/USE_COLOR="n"/' /etc/makepkg.conf
          sed -i 's/^#?GPGKEY=.*/GPGKEY=""/' /etc/makepkg.conf
          sed -i 's/^#?VERIFYSIG=.*/VERIFYSIG="n"/' /etc/makepkg.conf

      - name: Clone Mutter-git AUR PKGBUILD
        run: |
          sudo -u builder git clone https://aur.archlinux.org/mutter-git.git

      - name: Build Mutter package with makepkg
        run: |
          cd mutter-git
          sudo -u builder makepkg -s --noconfirm

      - name: Upload .pkg.tar.zst artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: mutter-git-pkg
          path: mutter-git/*.pkg.tar.zst
