name: Build Mutter-git inside Arch Linux container

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Mutter-git AUR repo
        run: |
          git clone https://aur.archlinux.org/mutter-git.git

      - name: Build inside Arch container
        run: |
          docker run --rm -v ${{ github.workspace }}:/build -w /build archlinux:base-devel bash -c "
            pacman -Syu --noconfirm &&
            pacman -S --noconfirm git sudo &&
            useradd -m builder &&
            echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers &&
            chown -R builder /build &&
            sed -i 's/^#?VERIFYSIG=.*/VERIFYSIG=\"n\"/' /etc/makepkg.conf &&
            cd mutter-git &&
            sudo -u builder makepkg -s --noconfirm
          "

      - name: Upload .pkg.tar.zst artifact
        uses: actions/upload-artifact@v3
        with:
          name: mutter-git-pkg
          path: mutter-git/*.pkg.tar.zst
